### ISSUE TITLE
Confusing command error messages

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli-db2-plugin#25]
When attempting to issue the following command (no profiles exist):

```
zowe db2 execute sql --query <query text>
```

I get the following response:
```
Command Error:
Expect Error: Required parameter 'hostname' must be defined
```

However, there is no `hostname` option. Only `host`:

```
   --host  | -H (string)

      The Db2 server host name
```

Also, this message differs from most other syntax errors e.g.:

```
Syntax Error:
You must specify one of the following options for this command:
[--query, --file]

Example:

 - Execute a dummy SQL query:

      $ zowe db2 execute sql --query"SELECT 'Hello World' FROM SYSIBM.SYSDUMMY1"

Use "zowe db2 execute sql --help" to view command description, usage, and options.
```

**Comment by zFernand0** [comment]
> ``` 
> You must specify one of the following options for this command:
> [--query, --file]
> ```

This is because there was no space in between the option an the value (`--query"SELECT`), hence why it was not identified as an option.

---

The `hostname` might be a legacy error message coming from the validation of `Imperative.ISession` properties (see [hostname validation code](https://github.com/zowe/imperative/blob/master/packages/rest/src/session/AbstractSession.ts#L244)). Ideally we would rename that property to just `host` but that's a breaking change and will have to wait for V3.

---

Closing in favor of:
- https://github.com/zowe/imperative/issues/953
